### ISSUE TITLE
[publisering] PDF-filnavnet bør gjenspeile spesifikasjonens navn

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/tbx-ap-no#13]
Navnet til PDF-filen som kan lastes ned er nå "document.pdf". 

Ønsker å ha et filnavn som gjenspeile spesifikasjonens navn, f.eks. repo-navnet (som også brukes i URLen til den gjeldende versjonen på data.norge.no).

**Comment by stigbd** [comment]
Fiksa i f66c6d805ea554c76d674f2eae5f681c3a54a2d2

**Comment by jimjyang** [comment]
Fiksa
