### ISSUE TITLE
Bruk av schematron fil i eksempler

### ISSUE THREAD

**Issue by OyvindLGjesdal** [Informasjonsforvaltning/tbx-ap-no#15]
Hei,

Eg lurer på om `TBX-AP-No_DCA.sch` finnes som en ressurs noe sted, og om den er tenkt brukt for validering av tbx-ap-no datasett? Inneholder den tilpasinger for tbx-ap-no som er på toppen av skjemaet i https://raw.githubusercontent.com/LTAC-Global/TBX_Core_RNG/master/TBXcoreStructV03.rng i TBX-AP-NO?

**Comment by jimjyang** [comment]
@OyvindLGjesdal 

Har nå lagt ut schematron-fila i undermappa [schematron](https://github.com/Informasjonsforvaltning/tbx-ap-no/tree/develop/schematron). Ja, den skulle inneholde tilpasninger i tbx-a-no. Husker dog ikke om den var forsøkt brukt den gang til validering av noen eksempler, derfor ingen garanti for at den er komplett/korrekt. Gi oss gjerne tilbakemeldinger hvis du finner feil eller mangler.

**Comment by OyvindLGjesdal** [comment]
Takk @jimjyang da kommer eg tilbake når vi har tatt den i bruk :)
