### ISSUE TITLE
Lenke til normativ ressurs ISO TBX virker ikke

### ISSUE THREAD

**Issue by rockphotog** [Informasjonsforvaltning/tbx-ap-no#53]
> [NS-ISO 30042:2019 Forvaltning av terminologiressurser - Utvekslingsformat for termbaser (TBX)](https://standard.no/no/Nettbutikk/produktkatalogen/Produktpresentasjon/?ProductID=1035256)

Jeg vet at Standard Norge har gjort om en god del på sine sider.

**Comment by jimjyang** [comment]
@rockphotog Takk skal du ha!
